[package]
name = "casc-extract"
version = "0.1.0"
authors = ["Flux Xu <fluxxu@gmail.com>"]

[dependencies]
casclib = { git = "https://github.com/wc3tools/casclib-rs.git" }
glob = "0.2.11"
toml = "0.2.1"
pbr = "1.0"